<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'UpdateHelper\\' => array($vendorDir . '/kylekatarnls/update-helper/src'),
    'Sabberworm\\CSS' => array($vendorDir . '/sabberworm/php-css-parser/lib'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'NumerosEnLetras' => array($vendorDir . '/villca/numeros-en-letras/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Milon\\Barcode' => array($vendorDir . '/milon/barcode/src'),
    'MaddHatter\\LaravelFullcalendar' => array($vendorDir . '/maddhatter/laravel-fullcalendar/src'),
    'Laracasts\\Flash' => array($vendorDir . '/laracasts/flash/src'),
    'Barryvdh' => array($vendorDir . '/barryvdh/reflection-docblock/src'),
);
